apiVersion: v1  
kind: Service  
metadata:  
  name: eureka-server-service 
  namespace: default
  labels:  
    app: eureka-server-service 
spec:
  type: NodePort  
  ports:  
    - port: 8761  
      nodePort: 30092 
  selector:  
    app: eureka-server 
