apiVersion: apps/v1 
kind: Deployment  
metadata:  
  name: eureka-server   
  labels:  
    app: eureka-server     
spec:  
  replicas: 1
  revisionHistoryLimit: 2
  selector:  
    matchLabels:  
      app: eureka-server 
  template:  
    metadata:  
      labels:  
        app: eureka-server   
    spec:  
      containers:  
      - name: eureka-server-container   
        image: lzw/eureka-server:1.0.0 
        ports:  
        - containerPort: 8761
          protocol: TCP  
        livenessProbe:  
          httpGet:  
            path: /
            port: 8761  
          initialDelaySeconds: 30  
          timeoutSeconds: 30  
        imagePullPolicy: IfNotPresent 
