apiVersion: v1  
kind: Service  
metadata:  
  name: user-service 
  namespace: default
  labels:  
    app: user-service 
spec:
  type: NodePort  
  ports:  
    - port: 8080  
      nodePort: 30091 
  selector:  
    app: user-service 
