apiVersion: apps/v1 
kind: Deployment  
metadata:  
  name: user-service  
  labels:  
    app: user-service    
spec:  
  replicas: 1
  revisionHistoryLimit: 2
  selector:  
    matchLabels:  
      app: user-service   
  template:  
    metadata:  
      labels:  
        app: user-service    
    spec:  
      containers:  
      - name: user-service-container   
        image: lzw/usermange:1.0.1 
        ports:  
        - containerPort: 8080
          protocol: TCP  
        livenessProbe:  
          httpGet:  
            path: /api/health 
            port: 8080  
          initialDelaySeconds: 30  
          timeoutSeconds: 30  
        imagePullPolicy: IfNotPresent 
