spring:
  datasource:
    username: root
    password: mysql
    url: jdbc:mysql://192.168.1.7:32306/dev?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
 
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: lzw.exapmle.spring.docker.entity
